import Head from 'next/head'
import Banner from '../components/Banner'
import SliderBanner from '../components/SliderBanner/SliderBanner'
import TravelTypes from '../components/TravelTypes/TravelTypes'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Worldtrip | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Banner />
      <TravelTypes />

      <SliderBanner />
      
    </div>
  )
}
